/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.extended;

import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.styling.StyleBuilder;
import org.opengis.filter.expression.Expression;

/**
 *
 * @author johann sorel
 */
public class JDashPanel extends javax.swing.JPanel {

    /** Creates new form JDashPanel */
    public JDashPanel() {
        initComponents();

        lbl_lenght.setText(TextBundle.getResource().getString("lenght"));
        lbl_between.setText(TextBundle.getResource().getString("gap"));
        lbl_offset.setText(TextBundle.getResource().getString("offset"));

        jsp_between.setFloatable(true);
        jsp_between.setMargins(0f, 65000f);
        jsp_lenght.setFloatable(true);
        jsp_lenght.setMargins(0f, 65000f);
        jsp_offset.setMargins(-65000f,65000f);
    }

    public float[] getDashes() {
        if (jsp_lenght.getFloatValue() == 0 || jsp_between.getFloatValue() == 0) {
            return new float[0];
        } else {
            float[] dashes = new float[2];
            dashes[0] = jsp_lenght.getFloatValue();
            dashes[1] = jsp_between.getFloatValue();
            return dashes;
        }
    }

    public void setDashes(float[] dashes) {

        if (dashes.length != 0) {
            jsp_lenght.setValue(dashes[0]);
            jsp_between.setValue(dashes[1]);
        }
    }
    
    public Expression getOffset(){
        StyleBuilder sb = new StyleBuilder();        
        return sb.literalExpression(jsp_offset.getFloatValue());
    }
    
    public void setOffset(Expression exp){
        
        if(exp != null)
            jsp_offset.setValue( Float.parseFloat(exp.toString()) );
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_lenght = new javax.swing.JLabel();
        jsp_lenght = new org.geotools.gui.swing.extended.JNumberPanel();
        jsp_between = new org.geotools.gui.swing.extended.JNumberPanel();
        lbl_between = new javax.swing.JLabel();
        lbl_offset = new javax.swing.JLabel();
        jsp_offset = new org.geotools.gui.swing.extended.JNumberPanel();

        lbl_lenght.setText("_");

        lbl_between.setText("_");

        lbl_offset.setText("_");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(lbl_lenght)
                .add(4, 4, 4)
                .add(jsp_lenght, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbl_between)
                .add(4, 4, 4)
                .add(jsp_between, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(lbl_offset)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jsp_offset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lbl_lenght)
                    .add(jsp_lenght, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbl_between)
                    .add(jsp_between, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jsp_offset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbl_offset)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.geotools.gui.swing.extended.JNumberPanel jsp_between;
    private org.geotools.gui.swing.extended.JNumberPanel jsp_lenght;
    private org.geotools.gui.swing.extended.JNumberPanel jsp_offset;
    private javax.swing.JLabel lbl_between;
    private javax.swing.JLabel lbl_lenght;
    private javax.swing.JLabel lbl_offset;
    // End of variables declaration//GEN-END:variables
}