package org.geotools.filter.function;


//this code is autogenerated - you shouldnt be modifying it!

import com.vividsolutions.jts.geom.*; //generic JTS support

import org.geotools.filter.expression.Expression;
import org.geotools.filter.expression.FunctionExpression;
import org.geotools.filter.expression.LiteralExpression;
import org.geotools.filter.function.StaticGeometry; //make sure you include this or you will not be able to call the functions!!


import org.geotools.feature.Feature;
import org.geotools.filter.FilterFactory;
import org.geotools.filter.FunctionExpressionImpl;


public class FilterFunction_in6 extends FunctionExpressionImpl implements FunctionExpression 
{


private Expression[] args; // list of args that this functions needs


public FilterFunction_in6()
{
}


public String getName()
{
      return "in6";
}

public int getArgCount()
{
      return 7;
}

public void setArgs(Expression[] args)
{
      this.args = args;
}

public Expression[] getArgs()
{
       return args;
}

public String toString()
{
       String result =  "in6(";
       for (int t=0;t<args.length;t++)
       {
                result += args[t] +",";
       }
       result += ")";
       return result;
}

public Object evaluate(Feature feature)
{
      Object  arg0;
      Object  arg1;
      Object  arg2;
      Object  arg3;
      Object  arg4;
      Object  arg5;
      Object  arg6;


      try{  //attempt to get value and perform conversion
                arg0 = (Object) args[0].getValue(feature);
      }
      catch (Exception e) // probably a type error
      {
            throw new IllegalArgumentException("Filter Function problem for function in6 argument #0 - expected type Object");
      }

      try{  //attempt to get value and perform conversion
                arg1 = (Object) args[1].getValue(feature);
      }
      catch (Exception e) // probably a type error
      {
            throw new IllegalArgumentException("Filter Function problem for function in6 argument #1 - expected type Object");
      }

      try{  //attempt to get value and perform conversion
                arg2 = (Object) args[2].getValue(feature);
      }
      catch (Exception e) // probably a type error
      {
            throw new IllegalArgumentException("Filter Function problem for function in6 argument #2 - expected type Object");
      }

      try{  //attempt to get value and perform conversion
                arg3 = (Object) args[3].getValue(feature);
      }
      catch (Exception e) // probably a type error
      {
            throw new IllegalArgumentException("Filter Function problem for function in6 argument #3 - expected type Object");
      }

      try{  //attempt to get value and perform conversion
                arg4 = (Object) args[4].getValue(feature);
      }
      catch (Exception e) // probably a type error
      {
            throw new IllegalArgumentException("Filter Function problem for function in6 argument #4 - expected type Object");
      }

      try{  //attempt to get value and perform conversion
                arg5 = (Object) args[5].getValue(feature);
      }
      catch (Exception e) // probably a type error
      {
            throw new IllegalArgumentException("Filter Function problem for function in6 argument #5 - expected type Object");
      }

      try{  //attempt to get value and perform conversion
                arg6 = (Object) args[6].getValue(feature);
      }
      catch (Exception e) // probably a type error
      {
            throw new IllegalArgumentException("Filter Function problem for function in6 argument #6 - expected type Object");
      }

      return new Boolean(StaticGeometry.in6(arg0,arg1,arg2,arg3,arg4,arg5,arg6 ));
}
}

