/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.contexttree;

import java.util.EventObject;

import org.geotools.map.MapContext;

/**
 * Event generated by JContextTree
 * @author johann sorel
 * 
 */
public class TreeSelectionEvent extends EventObject{
    
    private final SelectionData[] selection;
    
    
    /**
     * constructor
     * @param treetable the jcontexttree generating the event
     * @param SelectionData[] the selection
     */
    TreeSelectionEvent(JContextTree treetable, SelectionData[] selection) {
        super(treetable);
        this.selection = selection;
    }
    
    /**
     * return the SelectionData[]
     * @return array of selection, null is no selection
     */
    public SelectionData[] getSelection() {
        return this.selection;
    }
    
    
}
