
2005-05-11-14.10.20.431000
Verified successfully structure of table "Test"."Places" to import data into.

2005-05-11-14.10.20.441000
Start importing of 3 rows into table "Test"."Places"...

2005-05-11-14.10.20.451000
Using 3 rows per single INSERT statement.

2005-05-11-14.10.21.082000
Starting commit of block 1... (with 3 rows, first row: 1).
Committing block 1 succeeded.

2005-05-11-14.10.21.082001
Finished importing...

Total number of rows     = 3
Number of rows attempted = 3
Number of rows committed = 3
Number of rows rejected  = 0
Number of rows inserted, but not committed = 0

