
2005-05-11-14.10.28.362000
Created successfully table "Test"."Roads" to import data into.

2005-05-11-14.10.28.362001
Start importing of 87 rows into table "Test"."Roads"...

2005-05-11-14.10.28.362002
Using 87 rows per single INSERT statement.

2005-05-11-14.10.28.673000
Starting commit of block 1... (with 87 rows, first row: 1).
Committing block 1 succeeded.

2005-05-11-14.10.28.673001
Finished importing...

Total number of rows     = 87
Number of rows attempted = 87
Number of rows committed = 87
Number of rows rejected  = 0
Number of rows inserted, but not committed = 0

