package org.geotools.jdbc;

import java.sql.Connection;

/**
 * Primary key whose values are automatically generated.
 * 
 * @author Justin Deoliveira, The Open Planning Project
 *
 */
public class AutoGeneratedPrimaryKey extends PrimaryKey {

    protected AutoGeneratedPrimaryKey(String tableName, String columnName, Class type) {
        super(tableName, columnName, type);
        
    }

    public String generate(Connection cx, SQLDialect dialect) throws Exception {
        return null;
    }

}
