/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.styling.StyleBuilder;
import org.opengis.filter.expression.Expression;

/**
 *
 * @author johann sorel
 */
public class JDashPanel extends javax.swing.JPanel {

    /** 
     * Creates new form JDashPanel 
     */
    public JDashPanel() {
        initComponents();

        lbl_lenght.setText(TextBundle.getResource().getString("lenght"));
        lbl_between.setText(TextBundle.getResource().getString("gap"));
        lbl_offset.setText(TextBundle.getResource().getString("offset"));

        jsp_between.setFloatable(true);
        jsp_between.setMargins(0f, 65000f);
        jsp_lenght.setFloatable(true);
        jsp_lenght.setMargins(0f, 65000f);
        jsp_offset.setMargins(-65000f,65000f);
    }

    /**
     * 
     * @return float[]
     */
    public float[] getDashes() {
        if (jsp_lenght.getFloatValue() == 0 || jsp_between.getFloatValue() == 0) {
            return new float[0];
        } else {
            float[] dashes = new float[2];
            dashes[0] = jsp_lenght.getFloatValue();
            dashes[1] = jsp_between.getFloatValue();
            return dashes;
        }
    }

    /**
     * 
     * @param dashes , the default dashes array
     */
    public void setDashes(float[] dashes) {

        if (dashes.length != 0) {
            jsp_lenght.setValue(dashes[0]);
            jsp_between.setValue(dashes[1]);
        }
    }
    
    /**
     * 
     * @return Expression dashes offset
     */
    public Expression getOffset(){
        StyleBuilder sb = new StyleBuilder();        
        return sb.literalExpression(jsp_offset.getFloatValue());
    }

       
    /**
     * 
     * @param exp default dashes offset
     */
    public void setOffset(Expression exp){
        
        if(exp != null)
            jsp_offset.setValue( Float.parseFloat(exp.toString()) );
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsp_offset = new org.geotools.gui.swing.extended.JNumberPanel();
        lbl_offset = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_between = new javax.swing.JLabel();
        jsp_between = new org.geotools.gui.swing.extended.JNumberPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_lenght = new javax.swing.JLabel();
        jsp_lenght = new org.geotools.gui.swing.extended.JNumberPanel();

        lbl_offset.setText("_");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lbl_offset, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jsp_offset, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(lbl_offset)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jsp_offset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        lbl_between.setText("_");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lbl_between, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .add(jsp_between, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(lbl_between)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jsp_between, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        lbl_lenght.setText("_");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lbl_lenght, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .add(jsp_lenght, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(lbl_lenght)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jsp_lenght, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.geotools.gui.swing.extended.JNumberPanel jsp_between;
    private org.geotools.gui.swing.extended.JNumberPanel jsp_lenght;
    private org.geotools.gui.swing.extended.JNumberPanel jsp_offset;
    private javax.swing.JLabel lbl_between;
    private javax.swing.JLabel lbl_lenght;
    private javax.swing.JLabel lbl_offset;
    // End of variables declaration//GEN-END:variables
}