/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import java.awt.Color;
import org.geotools.factory.CommonFactoryFinder;
import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.map.MapLayer;
import org.geotools.styling.SLD;
import org.geotools.styling.StyleBuilder;
import org.opengis.filter.FilterFactory2;
import org.opengis.filter.expression.Expression;

/**
 *
 * @author  johann Sorel
 */
public class JExpressionPanel extends javax.swing.JPanel {

    private MapLayer layer;
    private JExpressionDialog dialog = new JExpressionDialog();
    private Expression exp = null;

    /** 
     * Creates new form JExpressionPanel 
     */
    public JExpressionPanel() {
        this(null, null);
    }

    /**
     * 
     * @param layer the layer style to edit
     */
    public JExpressionPanel(MapLayer layer) {
        this(layer, null);
    }

    /**
     * 
     * @param exp the default expression
     */
    public JExpressionPanel(Expression exp) {
        this(null, exp);
    }

    /**
     * 
     * @param layer the layer style to edit
     * @param exp the default expression
     */
    public JExpressionPanel(MapLayer layer, Expression exp) {
        initComponents();
        this.layer = layer;
        setExpression(exp);
    }

    /**
     * 
     * @param layer the layer style to edit
     */
    public void setLayer(MapLayer layer) {
        this.layer = layer;
    }

    /**
     * 
     * @param exp the default expression
     */
    public void setExpression(Expression exp) {

        if (exp != null) {
            if (exp != Expression.NIL) {
                txt.setText(exp.toString());
            }
        }

        if (exp != null) {

            if (exp.toString().startsWith("#")) {
                try {
                    Color col = SLD.color(exp);
                    if (col != null) {
                        txt.setBackground(col);
                    } else {
                        txt.setBackground(Color.WHITE);
                    }
                } catch (Exception e) {
                    txt.setBackground(Color.WHITE);
                }
            }
        } else {
            txt.setBackground(Color.WHITE);
        }
    }

    /**
     * 
     * @return Expression : new Expression
     */
    public Expression getExpression() {
        
//        FilterFactory2 ff = CommonFactoryFinder.getFilterFactory2(null);
//        Expression expr = ff.property(txt.getText());
//        
//        return expr;
        
        if(exp != null){
            return exp;
        }
        
        StyleBuilder sb = new StyleBuilder();
        return sb.literalExpression(txt.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFocusLost(evt);
            }
        });

        jButton1.setText(TextBundle.getResource().getString("shortexpression"));
        jButton1.setMargin(new java.awt.Insets(0, 3, 0, 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionDialog(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(txt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jButton1)
                .add(txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(new java.awt.Component[] {jButton1, txt}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void actionDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionDialog
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jButton1);
        dialog.setLayer(layer);
        dialog.setExpression(getExpression());
        dialog.setVisible(true);

        setExpression(dialog.getExpression());
        exp = dialog.getExpression();
    }//GEN-LAST:event_actionDialog

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        StyleBuilder sb = new StyleBuilder();
        exp = sb.literalExpression(txt.getText());
    }//GEN-LAST:event_txtActionPerformed

    private void txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFocusLost
        StyleBuilder sb = new StyleBuilder();
        exp = sb.literalExpression(txt.getText());
    }//GEN-LAST:event_txtFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}