/*
 * JExpressionPanel.java
 *
 * Created on 19 octobre 2007, 14:32
 */

package org.geotools.gui.swing.style.sld;

import java.awt.Color;
import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.map.MapLayer;
import org.geotools.styling.SLD;
import org.geotools.styling.StyleBuilder;
import org.opengis.feature.type.PropertyDescriptor;
import org.opengis.filter.expression.Expression;

/**
 *
 * @author  Administrateur
 */
public class JExpressionPanel extends javax.swing.JPanel {

    private MapLayer layer;
    private JExpressionDialog dialog = new JExpressionDialog();

    /** Creates new form JExpressionPanel */
    public JExpressionPanel() {
        this(null, null);
    }

    public JExpressionPanel(MapLayer layer) {
        this(layer, null);
    }

    public JExpressionPanel(Expression exp) {
        this(null, exp);
    }

    public JExpressionPanel(MapLayer layer, Expression exp) {
        initComponents();
        this.layer = layer;
        setExpression(exp);
    }

    public void setLayer(MapLayer layer) {
        this.layer = layer;
    }

    public void setExpression(Expression exp) {

        if (exp != null) {
            if (exp != Expression.NIL) {
                txt.setText(exp.toString());
            }
        }

        if (exp != null) {

            if (exp.toString().startsWith("#")) {
                try {
                    Color col = SLD.color(exp);
                    if (col != null) {
                        txt.setBackground(col);
                    } else {
                        txt.setBackground(Color.WHITE);
                    }
                } catch (Exception e) {
                    txt.setBackground(Color.WHITE);
                }
            }
        } else {
            txt.setBackground(Color.WHITE);
        }
    }

    public Expression getExpression() {
        StyleBuilder sb = new StyleBuilder();
        return sb.literalExpression(txt.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jButton1.setText(TextBundle.getResource().getString("shortexpression"));
        jButton1.setMargin(new java.awt.Insets(0, 3, 0, 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionDialog(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(txt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jButton1)
                .add(txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(new java.awt.Component[] {jButton1, txt}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void actionDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionDialog
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jButton1);
        dialog.setLayer(layer);
        dialog.setExpression(getExpression());
        dialog.setVisible(true);

        setExpression(dialog.getExpression());
    }//GEN-LAST:event_actionDialog
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}