/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.styling.StyleBuilder;
import org.opengis.filter.expression.Expression;

/**
 * @author  johann sorel
 */
public class JLinecapPanel extends javax.swing.JPanel {

    /** Creates new form JLinecapPanel */
    public JLinecapPanel() {
        initComponents();
        but_round.setIcon(IconBundle.getResource().getIcon("16_linecap_round"));
        but_butt.setIcon(IconBundle.getResource().getIcon("16_linecap_butt"));
        but_square.setIcon(IconBundle.getResource().getIcon("16_linecap_square"));

        but_round.setSelected(true);
    }

    public void setLineCap(String exp) {
        if (exp != null) {
            if (exp.toLowerCase().equals("butt")) {
                but_butt.setSelected(true);
            } else if (exp.toLowerCase().equals("square")) {
                but_square.setSelected(true);
            } else {
                but_round.setSelected(true);
            }
        }
    }

    public void setLineCap(Expression exp) {
        if (exp != null) {
            if (exp.toString().toLowerCase().equals("butt")) {
                but_butt.setSelected(true);
            } else if (exp.toString().toLowerCase().equals("square")) {
                but_square.setSelected(true);
            } else {
                but_round.setSelected(true);
            }
        }
    }

    public Expression getLinecap() {
        StyleBuilder sb = new StyleBuilder();

        if (but_butt.isSelected()) {
            return sb.literalExpression("butt");
        } else if (but_square.isSelected()) {
            return sb.literalExpression("square");
        } else {
            return sb.literalExpression("round");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        but_round = new javax.swing.JToggleButton();
        but_butt = new javax.swing.JToggleButton();
        but_square = new javax.swing.JToggleButton();

        buttonGroup1.add(but_round);
        but_round.setIconTextGap(0);
        but_round.setMargin(new java.awt.Insets(2, 2, 2, 2));

        buttonGroup1.add(but_butt);
        but_butt.setIconTextGap(0);
        but_butt.setMargin(new java.awt.Insets(2, 2, 2, 2));

        buttonGroup1.add(but_square);
        but_square.setIconTextGap(0);
        but_square.setMargin(new java.awt.Insets(2, 2, 2, 2));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(but_round)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_butt)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_square))
        );

        layout.linkSize(new java.awt.Component[] {but_butt, but_round, but_square}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(but_round)
            .add(but_butt)
            .add(but_square)
        );

        layout.linkSize(new java.awt.Component[] {but_butt, but_round, but_square}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton but_butt;
    private javax.swing.JToggleButton but_round;
    private javax.swing.JToggleButton but_square;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}