/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.styling.StyleBuilder;
import org.opengis.filter.expression.Expression;

/**
 *
 * @author  johann sorel
 */
public class JLinejoinPanel extends javax.swing.JPanel {
    
    /** Creates new form JLinecapPanel */
    public JLinejoinPanel() {
        initComponents();
        but_round.setIcon( IconBundle.getResource().getIcon("16_linejoin_round"));
        but_mitre.setIcon( IconBundle.getResource().getIcon("16_linejoin_mitre"));
        but_bevel.setIcon( IconBundle.getResource().getIcon("16_linejoin_bevel"));
        
        but_round.setSelected(true);
    }
    
    
    public void setLineJoin(String exp){
                
        if( "bevel".equals(exp.toLowerCase()) )
            but_bevel.setSelected(true);
        else if( "mitre".equals(exp.toLowerCase()) )
            but_mitre.setSelected(true);
        else 
            but_round.setSelected(true);        
    }
    
    public void setLineJoin(Expression exp){
                
        if( "bevel".equals(exp.toString().toLowerCase()) )
            but_bevel.setSelected(true);
        else if( "mitre".equals(exp.toString().toLowerCase()) )
            but_mitre.setSelected(true);
        else 
            but_round.setSelected(true);        
    }
       
    
    public Expression getLineJoin(){
        StyleBuilder sb = new StyleBuilder();
        
        if(but_bevel.isSelected())
            return sb.literalExpression("bevel");
        else if(but_mitre.isSelected())
            return sb.literalExpression("mitre");
        else
            return sb.literalExpression("round");        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        but_round = new javax.swing.JToggleButton();
        but_bevel = new javax.swing.JToggleButton();
        but_mitre = new javax.swing.JToggleButton();

        buttonGroup1.add(but_round);
        but_round.setIconTextGap(0);
        but_round.setMargin(new java.awt.Insets(2, 2, 2, 2));

        buttonGroup1.add(but_bevel);
        but_bevel.setIconTextGap(0);
        but_bevel.setMargin(new java.awt.Insets(2, 2, 2, 2));

        buttonGroup1.add(but_mitre);
        but_mitre.setIconTextGap(0);
        but_mitre.setMargin(new java.awt.Insets(2, 2, 2, 2));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(but_round)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_bevel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_mitre))
        );

        layout.linkSize(new java.awt.Component[] {but_bevel, but_mitre, but_round}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(but_round)
            .add(but_bevel)
            .add(but_mitre)
        );

        layout.linkSize(new java.awt.Component[] {but_bevel, but_mitre, but_round}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton but_bevel;
    private javax.swing.JToggleButton but_mitre;
    private javax.swing.JToggleButton but_round;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
    
}
