/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.map.MapLayer;
import org.geotools.styling.StyleBuilder;
import org.opengis.filter.expression.Expression;

/**
 * @author  johann sorel
 */
public class JLinecapPanel extends javax.swing.JPanel {

    
    private Expression exp = null;
    private MapLayer layer = null;    
    
    
    
    /** 
     * Creates new form JLinecapPanel 
     */
    public JLinecapPanel() {
        initComponents();

        
        
        but_round.setSelected(true);
    }

    /**
     * 
     * @param layer the layer style to edit
     */
    public void setLayer(MapLayer layer) {
        this.layer = layer;
    }
    
    /**
     * 
     * @param exp String Expression of LineCap
     */
    public void setLineCap(String exp) {
        if (exp != null) {
            if (exp.toLowerCase().equals("butt")) {
                but_butt.setSelected(true);
            } else if (exp.toLowerCase().equals("square")) {
                but_square.setSelected(true);
            } else {
                but_round.setSelected(true);
            }
        }
    }

    /**
     * 
     * @param exp Expression of LineCap
     */
    public void setLineCap(Expression exp) {
        this.exp = exp;
        if (exp != null) {
            if (exp.toString().toLowerCase().equals("butt")) {
                but_butt.setSelected(true);
            } else if (exp.toString().toLowerCase().equals("square")) {
                but_square.setSelected(true);
            } else if (exp.toString().toLowerCase().equals("round")) {
                but_round.setSelected(true);
            }
        }
    }

    /**
     * 
     * @return new Expression of LineCap
     */
    public Expression getLinecap() {
        
        
        if(exp != null){
            return exp;
        }else{
            StyleBuilder sb = new StyleBuilder();
            return sb.literalExpression("round");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        but_round = new javax.swing.JToggleButton();
        but_butt = new javax.swing.JToggleButton();
        but_square = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        buttonGroup1.add(but_round);
        but_round.setIcon(IconBundle.getResource().getIcon("16_linecap_round"));
        but_round.setText(" ");
        but_round.setIconTextGap(0);
        but_round.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but_round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_roundActionPerformed(evt);
            }
        });

        buttonGroup1.add(but_butt);
        but_butt.setIcon(IconBundle.getResource().getIcon("16_linecap_butt"));
        but_butt.setText(" ");
        but_butt.setIconTextGap(0);
        but_butt.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_buttActionPerformed(evt);
            }
        });

        buttonGroup1.add(but_square);
        but_square.setIcon(IconBundle.getResource().getIcon("16_linecap_square"));
        but_square.setText(" ");
        but_square.setIconTextGap(0);
        but_square.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but_square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_squareActionPerformed(evt);
            }
        });

        jButton1.setText(TextBundle.getResource().getString("shortexpression"));
        jButton1.setMargin(new java.awt.Insets(0, 3, 0, 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1actionDialogLineCap(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(but_round)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_butt)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_square)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(but_round, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(but_butt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(but_square, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {but_butt, but_round, but_square, jButton1}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void but_squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_squareActionPerformed
        StyleBuilder sb = new StyleBuilder();
        exp = sb.literalExpression("square");
    }//GEN-LAST:event_but_squareActionPerformed

    private void jButton1actionDialogLineCap(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1actionDialogLineCap
        JExpressionDialog dialog = new JExpressionDialog();
        
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jButton1);
        dialog.setLayer(layer);
        dialog.setExpression(exp);
        dialog.setVisible(true);
        
        exp = dialog.getExpression();
        
        but_butt.setSelected(false);
        but_round.setSelected(false);
        but_square.setSelected(false);
    }//GEN-LAST:event_jButton1actionDialogLineCap

    private void but_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_buttActionPerformed
          StyleBuilder sb = new StyleBuilder();
          exp = sb.literalExpression("butt");
    }//GEN-LAST:event_but_buttActionPerformed

    private void but_roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_roundActionPerformed
        StyleBuilder sb = new StyleBuilder();
        exp = sb.literalExpression("round");
    }//GEN-LAST:event_but_roundActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton but_butt;
    private javax.swing.JToggleButton but_round;
    private javax.swing.JToggleButton but_square;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}