/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.map.MapLayer;
import org.geotools.styling.StyleBuilder;
import org.opengis.filter.expression.Expression;

/**
 *
 * @author  johann sorel
 */
public class JLinejoinPanel extends javax.swing.JPanel {
    
    private MapLayer layer = null;
    private Expression exp = null;
    
    
    /** 
     * Creates new form JLinecapPanel 
     */
    public JLinejoinPanel() {
        initComponents();
        but_round.setIcon( IconBundle.getResource().getIcon("16_linejoin_round"));
        but_mitre.setIcon( IconBundle.getResource().getIcon("16_linejoin_mitre"));
        but_bevel.setIcon( IconBundle.getResource().getIcon("16_linejoin_bevel"));
        
        but_round.setSelected(true);
    }
    
    /**
     * 
     * @param layer the layer style to edit
     */
    public void setLayer(MapLayer layer) {
        this.layer = layer;
    }
    
    
    /**
     * 
     * @param exp String to parse
     */
    public void setLineJoin(String exp){
                
        if( "bevel".equals(exp.toLowerCase()) )
            but_bevel.setSelected(true);
        else if( "mitre".equals(exp.toLowerCase()) )
            but_mitre.setSelected(true);
        else 
            but_round.setSelected(true);        
    }
    
    /**
     * 
     * @param exp Expression of the linejoin
     */
    public void setLineJoin(Expression exp){
                
        this.exp = exp;
        if (exp != null) {
            if (exp.toString().toLowerCase().equals("bevel")) {
                but_bevel.setSelected(true);
            } else if (exp.toString().toLowerCase().equals("mitre")) {
                but_mitre.setSelected(true);
            } else if (exp.toString().toLowerCase().equals("round")) {
                but_round.setSelected(true);
            }
        }
              
    }
       
    
    /**
     * 
     * @return Expression : new Expression of LineJoin
     */
    public Expression getLineJoin(){
        
        if(exp != null){
            return exp;
        }else{
            StyleBuilder sb = new StyleBuilder();
            return sb.literalExpression("round");
        }
               
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        but_round = new javax.swing.JToggleButton();
        but_bevel = new javax.swing.JToggleButton();
        but_mitre = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        buttonGroup1.add(but_round);
        but_round.setIconTextGap(0);
        but_round.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but_round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_roundActionPerformed(evt);
            }
        });

        buttonGroup1.add(but_bevel);
        but_bevel.setIconTextGap(0);
        but_bevel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but_bevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_bevelActionPerformed(evt);
            }
        });

        buttonGroup1.add(but_mitre);
        but_mitre.setText(" ");
        but_mitre.setIconTextGap(0);
        but_mitre.setMargin(new java.awt.Insets(2, 2, 2, 2));
        but_mitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_mitreActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/geotools/gui/swing/style/sld/Bundle"); // NOI18N
        jButton1.setText(bundle.getString("shortexpression")); // NOI18N
        jButton1.setMargin(new java.awt.Insets(0, 3, 0, 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1actionDialogLineCap(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(but_round)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_bevel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_mitre)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
            .add(but_round)
            .add(but_bevel)
            .add(but_mitre)
            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        layout.linkSize(new java.awt.Component[] {but_bevel, but_mitre, but_round, jButton1}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1actionDialogLineCap(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1actionDialogLineCap
        JExpressionDialog dialog = new JExpressionDialog();
        
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jButton1);
        dialog.setLayer(layer);
        dialog.setExpression(exp);
        dialog.setVisible(true);
        
        exp = dialog.getExpression();
        
        but_bevel.setSelected(false);
        but_round.setSelected(false);
        but_mitre.setSelected(false);
    }//GEN-LAST:event_jButton1actionDialogLineCap

    private void but_roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_roundActionPerformed
       StyleBuilder sb = new StyleBuilder();
       exp = sb.literalExpression("round");   
    }//GEN-LAST:event_but_roundActionPerformed

    private void but_bevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_bevelActionPerformed
        StyleBuilder sb = new StyleBuilder();
        exp = sb.literalExpression("bevel");
    }//GEN-LAST:event_but_bevelActionPerformed

    private void but_mitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_mitreActionPerformed
        StyleBuilder sb = new StyleBuilder();
        exp = sb.literalExpression("mitre");
    }//GEN-LAST:event_but_mitreActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton but_bevel;
    private javax.swing.JToggleButton but_mitre;
    private javax.swing.JToggleButton but_round;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    
    
}
