/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.style.StyleFeatureEditor;
import org.geotools.map.MapLayer;
import org.geotools.styling.Mark;
import org.geotools.styling.StyleBuilder;

/**
 *
 * @author johann sorel
 */
public class JMarkPane extends javax.swing.JPanel implements StyleFeatureEditor{
    
    private MapLayer layer = null;
    private Mark mark = null;
    
    /** Creates new form JDisplacementPanel */
    public JMarkPane() {
        initComponents();
        init();
    }
    
    private void init(){
    }
    
    public void setLayer(MapLayer layer){
        this.layer = layer;
    }
    
    public MapLayer getLayer(){
        return layer;
    }
    
    public void setMark(Mark mk){
        this.mark = mk;
        
        if(mark != null){          
        }
    }
    
    public Mark getMark(){
        
        if(mark == null){
            StyleBuilder sb = new StyleBuilder();
            mark = sb.createMark("triangle");
        }
        
        apply();
        return mark;
    }
            
    public void apply(){
        if(mark != null){
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
