/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.gui.swing.style.sld;

import org.geotools.map.MapLayer;
import org.geotools.styling.Stroke;
import org.geotools.styling.StyleBuilder;

/**
 *
 * @author johann sorel
 */
public class JStrokePanel extends javax.swing.JPanel {

    //private StyleBuilder sb = new StyleBuilder();
    //private JExpressionDialog dialog = new JExpressionDialog();
    private MapLayer layer = null;

    /** 
     * Creates new form JStrokePanel 
     */
    public JStrokePanel() {
        super();
        initComponents();
        init();

    }

    private void init() {
        GuiStrokeWidth.setType(JExpressionPanel.EXP_TYPE.NUMBER);
        GuiStrokeAlpha.setType(JExpressionPanel.EXP_TYPE.NUMBER);
        GuiStrokeColor.setType(JExpressionPanel.EXP_TYPE.COLOR);
    }

    /**
     * 
     * @param layer the layer style to edit
     */
    public void setLayer(MapLayer layer) {
        this.layer = layer;
        GuiStrokeWidth.setLayer(layer);
        GuiStrokeColor.setLayer(layer);
        GuiStrokeAlpha.setLayer(layer);
        GuiStrokeLineCap.setLayer(layer);
        GuiStrokeLineJoin.setLayer(layer);
    }

    /**
     * 
     * @param stroke the stroke to edit
     */
    public void parseStroke(Stroke stroke) {
        if (stroke != null) {
            // TODO : not yet implemented
            //Graphic graf = stroke.getGraphicFill();
            //Graphic gras = stroke.getGraphicStroke();
            GuiStrokeLineCap.setLineCap(stroke.getLineCap());
            GuiStrokeLineJoin.setLineJoin(stroke.getLineJoin());
            GuiStrokeDashes.setDashes(stroke.getDashArray());
            GuiStrokeDashes.setOffset(stroke.getDashOffset());
            GuiStrokeWidth.setExpression(stroke.getWidth());
            GuiStrokeColor.setExpression(stroke.getColor());
            GuiStrokeAlpha.setExpression(stroke.getOpacity());
        }
    }

    /**
     * 
     * @return Stroke : a new Stroke result from the edit panel
     */
    public Stroke getStroke() {
        StyleBuilder sb = new StyleBuilder();

        Stroke stroke = sb.createStroke(GuiStrokeColor.getExpression(), GuiStrokeWidth.getExpression());
        stroke.setLineCap(GuiStrokeLineCap.getLinecap());
        stroke.setLineJoin(GuiStrokeLineJoin.getLineJoin());
        stroke.setDashArray(GuiStrokeDashes.getDashes());
        stroke.setDashOffset(GuiStrokeDashes.getOffset());
        stroke.setOpacity(GuiStrokeAlpha.getExpression());

        return stroke;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuiStrokeDashes = new org.geotools.gui.swing.style.sld.JDashPanel();
        jPanel2 = new javax.swing.JPanel();
        GuiStrokeLineCap = new org.geotools.gui.swing.style.sld.JLinecapPanel();
        GuiStrokeLineJoin = new org.geotools.gui.swing.style.sld.JLinejoinPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_b_width = new javax.swing.JLabel();
        GuiStrokeWidth = new org.geotools.gui.swing.style.sld.JExpressionPanel();
        lbl_b_color = new javax.swing.JLabel();
        GuiStrokeColor = new org.geotools.gui.swing.style.sld.JExpressionPanel();
        lbl_b_alpha = new javax.swing.JLabel();
        GuiStrokeAlpha = new org.geotools.gui.swing.style.sld.JExpressionPanel();

        GuiStrokeDashes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(GuiStrokeLineCap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(GuiStrokeLineJoin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(GuiStrokeLineJoin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(GuiStrokeLineCap, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/geotools/gui/swing/style/sld/Bundle"); // NOI18N
        lbl_b_width.setText(bundle.getString("width")); // NOI18N

        lbl_b_color.setText(bundle.getString("color")); // NOI18N

        lbl_b_alpha.setText(bundle.getString("opacity")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_b_width)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GuiStrokeWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_b_color)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GuiStrokeColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_b_alpha)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GuiStrokeAlpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_width, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_color, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_alpha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeAlpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(GuiStrokeDashes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeDashes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.geotools.gui.swing.style.sld.JExpressionPanel GuiStrokeAlpha;
    private org.geotools.gui.swing.style.sld.JExpressionPanel GuiStrokeColor;
    private org.geotools.gui.swing.style.sld.JDashPanel GuiStrokeDashes;
    private org.geotools.gui.swing.style.sld.JLinecapPanel GuiStrokeLineCap;
    private org.geotools.gui.swing.style.sld.JLinejoinPanel GuiStrokeLineJoin;
    private org.geotools.gui.swing.style.sld.JExpressionPanel GuiStrokeWidth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_b_alpha;
    private javax.swing.JLabel lbl_b_color;
    private javax.swing.JLabel lbl_b_width;
    // End of variables declaration//GEN-END:variables
}
