/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.gui.swing.style.sld;

import java.awt.Component;
import javax.swing.Icon;
import javax.swing.JDialog;
import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.gui.swing.style.StyleElementEditor;
import org.geotools.map.MapLayer;
import org.geotools.styling.Stroke;
import org.geotools.styling.StyleBuilder;

/**
 *
 * @author johann sorel
 */
public class JStrokePane extends javax.swing.JPanel implements StyleElementEditor<Stroke>{
    
    private static final Icon ICO_GRAPHIC = IconBundle.getResource().getIcon("16_paint_fill");    
    private MapLayer layer = null;
    private Stroke stroke = null;

    /** 
     * Creates new form JStrokePanel 
     */
    public JStrokePane() {
        super();
        initComponents();
        init();

    }

    private void init() {
        GuiStrokeWidth.setType(JExpressionPane.EXP_TYPE.NUMBER);
        GuiStrokeAlpha.setType(JExpressionPane.EXP_TYPE.OPACITY);
        GuiStrokeColor.setType(JExpressionPane.EXP_TYPE.COLOR);
    }

    public void setLayer(MapLayer layer) {
        this.layer = layer;
        GuiStrokeWidth.setLayer(layer);
        GuiStrokeColor.setLayer(layer);
        GuiStrokeAlpha.setLayer(layer);
        GuiStrokeLineCap.setLayer(layer);
        GuiStrokeLineJoin.setLayer(layer);
    }    
    
    public MapLayer getLayer() {
        return layer;
    }

    public void setEdited(Stroke stroke) {
        
        this.stroke = stroke;
            
        if (stroke != null) {
//            implemented using two buttons
//            stroke.getGraphicFill();
//            stroke.getGraphicStroke();            
            GuiStrokeLineCap.setLineCap(stroke.getLineCap());
            GuiStrokeLineJoin.setLineJoin(stroke.getLineJoin());
            GuiStrokeDashes.setDashes(stroke.getDashArray());
            GuiStrokeDashes.setOffset(stroke.getDashOffset());
            GuiStrokeWidth.setExpression(stroke.getWidth());
            GuiStrokeColor.setExpression(stroke.getColor());
            GuiStrokeAlpha.setExpression(stroke.getOpacity());
        }
        
    }

    public Stroke getEdited() {
        
        if(stroke == null){
            StyleBuilder sb = new StyleBuilder();
            stroke = sb.createStroke(GuiStrokeColor.getExpression(), GuiStrokeWidth.getExpression());
        }

        apply();
        return stroke;
    }

    public void apply(){
        if(stroke != null){
            stroke.setLineCap(GuiStrokeLineCap.getLineCap());
            stroke.setLineJoin(GuiStrokeLineJoin.getLineJoin());
            stroke.setDashArray(GuiStrokeDashes.getDashes());
            stroke.setDashOffset(GuiStrokeDashes.getOffset());
            stroke.setOpacity(GuiStrokeAlpha.getExpression());
            stroke.setWidth(GuiStrokeWidth.getExpression());
            stroke.setColor(GuiStrokeColor.getExpression());
        }
    }
        
    public Component getComponent() {
        return this;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuiStrokeDashes = new org.geotools.gui.swing.style.sld.JDashPane();
        jPanel2 = new javax.swing.JPanel();
        GuiStrokeLineCap = new org.geotools.gui.swing.style.sld.JLinecapPane();
        GuiStrokeLineJoin = new org.geotools.gui.swing.style.sld.JLinejoinPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_b_width = new javax.swing.JLabel();
        GuiStrokeWidth = new org.geotools.gui.swing.style.sld.JExpressionPane();
        lbl_b_color = new javax.swing.JLabel();
        GuiStrokeColor = new org.geotools.gui.swing.style.sld.JExpressionPane();
        lbl_b_alpha = new javax.swing.JLabel();
        GuiStrokeAlpha = new org.geotools.gui.swing.style.sld.JExpressionPane();
        butStroke = new javax.swing.JButton();
        butFill = new javax.swing.JButton();

        GuiStrokeDashes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(GuiStrokeLineCap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                .add(GuiStrokeLineJoin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(GuiStrokeLineJoin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(GuiStrokeLineCap, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/geotools/gui/swing/style/sld/Bundle"); // NOI18N
        lbl_b_width.setText(bundle.getString("width")); // NOI18N

        lbl_b_color.setText(bundle.getString("color")); // NOI18N

        lbl_b_alpha.setText(bundle.getString("opacity")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_b_width)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GuiStrokeWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_b_color)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GuiStrokeColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_b_alpha)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GuiStrokeAlpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_width, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_color, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbl_b_alpha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GuiStrokeAlpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        butStroke.setIcon(ICO_GRAPHIC);
        butStroke.setText(bundle.getString("stroke")); // NOI18N
        butStroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStrokeActionPerformed(evt);
            }
        });

        butFill.setIcon(ICO_GRAPHIC);
        butFill.setText(bundle.getString("fill")); // NOI18N
        butFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFillActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(GuiStrokeDashes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 276, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(butFill, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .add(butStroke, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(butStroke)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butFill)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GuiStrokeDashes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butStrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStrokeActionPerformed
                
        JDialog dia = new JDialog();
        
        JGraphicPane pane = new JGraphicPane();
        pane.setLayer(layer);
        
        if(stroke != null){
            pane.setEdited(stroke.getGraphicStroke());
        }
        
        dia.setContentPane(pane);
        dia.pack();
        dia.setLocationRelativeTo(butStroke);
        dia.setModal(true);
        dia.setVisible(true);
        
        if(stroke == null){
            stroke =  new StyleBuilder().createStroke() ;
        }
        stroke.setGraphicStroke(pane.getEdited());
        
}//GEN-LAST:event_butStrokeActionPerformed

    private void butFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFillActionPerformed
        
        JDialog dia = new JDialog();
        
        JGraphicPane pane = new JGraphicPane();
        pane.setLayer(layer);
        
        if(stroke != null){
            pane.setEdited(stroke.getGraphicFill());
        }
        
        dia.setContentPane(pane);
        dia.pack();
        dia.setLocationRelativeTo(butFill);
        dia.setModal(true);
        dia.setVisible(true);
        
        if(stroke == null){
            stroke =  new StyleBuilder().createStroke() ;
        }
        stroke.setGraphicFill(pane.getEdited());
        
    }//GEN-LAST:event_butFillActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.geotools.gui.swing.style.sld.JExpressionPane GuiStrokeAlpha;
    private org.geotools.gui.swing.style.sld.JExpressionPane GuiStrokeColor;
    private org.geotools.gui.swing.style.sld.JDashPane GuiStrokeDashes;
    private org.geotools.gui.swing.style.sld.JLinecapPane GuiStrokeLineCap;
    private org.geotools.gui.swing.style.sld.JLinejoinPane GuiStrokeLineJoin;
    private org.geotools.gui.swing.style.sld.JExpressionPane GuiStrokeWidth;
    private javax.swing.JButton butFill;
    private javax.swing.JButton butStroke;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_b_alpha;
    private javax.swing.JLabel lbl_b_color;
    private javax.swing.JLabel lbl_b_width;
    // End of variables declaration//GEN-END:variables


}
