/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.styling.Stroke;
import org.geotools.styling.StyleBuilder;
import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;

/**
 *
 * @author johann sorel
 */
public class JStrokePanel extends javax.swing.JPanel {

    /** Creates new form JStrokePanel */
    public JStrokePanel() {
        initComponents();
        
        GuiStrokeAlpha.setMargins(0, 1);
        GuiStrokeAlpha.setFloatable(true);
        GuiStrokeWidth.setMargins(0, 65000);
        GuiStrokeWidth.setFloatable(false);
        
    }

    public void parseStroke(Stroke stroke) {
        if (stroke != null) {
            // TODO : not yet implemented
            //Graphic graf = stroke.getGraphicFill();
            //Graphic gras = stroke.getGraphicStroke();
            GuiStrokeLineCap.setLineCap(stroke.getLineCap());
            GuiStrokeLineJoin.setLineJoin(stroke.getLineJoin());
            GuiStrokeDashes.setDashes(stroke.getDashArray());
            GuiStrokeDashes.setOffset(stroke.getDashOffset());
            GuiStrokeWidth.setValue(stroke.getWidth());
            GuiStrokeColor.setColor(stroke.getColor());
            GuiStrokeAlpha.setValue(stroke.getOpacity());
        }
    }

    public Stroke getStroke() {
        StyleBuilder sb = new StyleBuilder();

        Stroke stroke = sb.createStroke(GuiStrokeColor.getExpressionColor(), GuiStrokeWidth.getExpressionValue());
        stroke.setLineCap(GuiStrokeLineCap.getLinecap());
        stroke.setLineJoin(GuiStrokeLineJoin.getLineJoin());
        stroke.setDashArray(GuiStrokeDashes.getDashes());
        stroke.setDashOffset(GuiStrokeDashes.getOffset());
        stroke.setOpacity(GuiStrokeAlpha.getExpressionValue());
        
        return stroke;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuiStrokeDashes = new org.geotools.gui.swing.style.sld.JDashPanel();
        jPanel1 = new javax.swing.JPanel();
        GuiStrokeAlpha = new org.geotools.gui.swing.extended.JNumberPanel();
        lbl_b_alpha = new javax.swing.JLabel();
        lbl_b_color = new javax.swing.JLabel();
        GuiStrokeColor = new org.geotools.gui.swing.style.sld.JColorPanel();
        GuiStrokeWidth = new org.geotools.gui.swing.extended.JNumberPanel();
        lbl_b_width = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GuiStrokeLineCap = new org.geotools.gui.swing.style.sld.JLinecapPanel();
        GuiStrokeLineJoin = new org.geotools.gui.swing.style.sld.JLinejoinPanel();
        jSeparator1 = new javax.swing.JSeparator();

        lbl_b_alpha.setText(TextBundle.getResource().getString("opacity"));

        lbl_b_color.setText(TextBundle.getResource().getString("color"));

        GroupLayout GuiStrokeColorLayout = new GroupLayout(GuiStrokeColor);
        GuiStrokeColor.setLayout(GuiStrokeColorLayout);
        GuiStrokeColorLayout.setHorizontalGroup(
            GuiStrokeColorLayout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 61, Short.MAX_VALUE)
        );
        GuiStrokeColorLayout.setVerticalGroup(
            GuiStrokeColorLayout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 18, Short.MAX_VALUE)
        );

        lbl_b_width.setText(TextBundle.getResource().getString("width"));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(lbl_b_width)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(GuiStrokeWidth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(lbl_b_color)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(GuiStrokeColor, GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(lbl_b_alpha)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(GuiStrokeAlpha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(GroupLayout.TRAILING)
                    .add(GuiStrokeWidth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .add(lbl_b_width))
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(GroupLayout.TRAILING)
                    .add(lbl_b_color)
                    .add(GuiStrokeColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(GroupLayout.TRAILING)
                    .add(GuiStrokeAlpha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .add(lbl_b_alpha)))
        );

        GuiStrokeLineCap.setBackground(new java.awt.Color(255, 255, 255));
        GuiStrokeLineCap.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GuiStrokeLineJoin.setBackground(new java.awt.Color(255, 255, 255));
        GuiStrokeLineJoin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.LEADING)
            .add(GuiStrokeLineCap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .add(GuiStrokeLineJoin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(GuiStrokeLineCap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(GuiStrokeLineJoin, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(jSeparator1, GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(GuiStrokeDashes, GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(GuiStrokeDashes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.geotools.gui.swing.extended.JNumberPanel GuiStrokeAlpha;
    private org.geotools.gui.swing.style.sld.JColorPanel GuiStrokeColor;
    private org.geotools.gui.swing.style.sld.JDashPanel GuiStrokeDashes;
    private org.geotools.gui.swing.style.sld.JLinecapPanel GuiStrokeLineCap;
    private org.geotools.gui.swing.style.sld.JLinejoinPanel GuiStrokeLineJoin;
    private org.geotools.gui.swing.extended.JNumberPanel GuiStrokeWidth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_b_alpha;
    private javax.swing.JLabel lbl_b_color;
    private javax.swing.JLabel lbl_b_width;
    // End of variables declaration//GEN-END:variables
}