/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.style.sld;

import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.styling.Stroke;
import org.geotools.styling.StyleBuilder;

/**
 *
 * @author johann sorel
 */
public class JStrokePanel extends javax.swing.JPanel {

    /** Creates new form JStrokePanel */
    public JStrokePanel() {
        initComponents();
        
        GuiStrokeAlpha.setMargins(0, 1);
        GuiStrokeAlpha.setFloatable(true);
        GuiStrokeWidth.setMargins(0, 65000);
        GuiStrokeWidth.setFloatable(false);
        
    }

    public void parseStroke(Stroke stroke) {
        if (stroke != null) {
            // TODO : not yet implemented
            //Graphic graf = stroke.getGraphicFill();
            //Graphic gras = stroke.getGraphicStroke();
            GuiStrokeLineCap.setLineCap(stroke.getLineCap());
            GuiStrokeLineJoin.setLineJoin(stroke.getLineJoin());
            GuiStrokeDashes.setDashes(stroke.getDashArray());
            GuiStrokeDashes.setOffset(stroke.getDashOffset());
            GuiStrokeWidth.setValue(stroke.getWidth());
            GuiStrokeColor.setColor(stroke.getColor());
            GuiStrokeAlpha.setValue(stroke.getOpacity());
        }
    }

    public Stroke getStroke() {
        StyleBuilder sb = new StyleBuilder();

        Stroke stroke = sb.createStroke(GuiStrokeColor.getExpressionColor(), GuiStrokeWidth.getExpressionValue());
        stroke.setLineCap(GuiStrokeLineCap.getLinecap());
        stroke.setLineJoin(GuiStrokeLineJoin.getLineJoin());
        stroke.setDashArray(GuiStrokeDashes.getDashes());
        stroke.setDashOffset(GuiStrokeDashes.getOffset());
        stroke.setOpacity(GuiStrokeAlpha.getExpressionValue());
        
        return stroke;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuiStrokeDashes = new org.geotools.gui.swing.style.sld.JDashPanel();
        jPanel1 = new javax.swing.JPanel();
        GuiStrokeAlpha = new org.geotools.gui.swing.extended.JNumberPanel();
        lbl_b_alpha = new javax.swing.JLabel();
        lbl_b_color = new javax.swing.JLabel();
        GuiStrokeColor = new org.geotools.gui.swing.style.sld.JColorPanel();
        GuiStrokeWidth = new org.geotools.gui.swing.extended.JNumberPanel();
        lbl_b_width = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GuiStrokeLineCap = new org.geotools.gui.swing.style.sld.JLinecapPanel();
        GuiStrokeLineJoin = new org.geotools.gui.swing.style.sld.JLinejoinPanel();
        jSeparator1 = new javax.swing.JSeparator();

        lbl_b_alpha.setText(TextBundle.getResource().getString("opacity"));

        lbl_b_color.setText(TextBundle.getResource().getString("color"));

        javax.swing.GroupLayout GuiStrokeColorLayout = new javax.swing.GroupLayout(GuiStrokeColor);
        GuiStrokeColor.setLayout(GuiStrokeColorLayout);
        GuiStrokeColorLayout.setHorizontalGroup(
            GuiStrokeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        GuiStrokeColorLayout.setVerticalGroup(
            GuiStrokeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        lbl_b_width.setText(TextBundle.getResource().getString("width"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_b_width)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuiStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_b_color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuiStrokeColor, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_b_alpha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuiStrokeAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuiStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_b_width))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_b_color)
                    .addComponent(GuiStrokeColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuiStrokeAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_b_alpha)))
        );

        GuiStrokeLineCap.setBackground(new java.awt.Color(255, 255, 255));
        GuiStrokeLineCap.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GuiStrokeLineJoin.setBackground(new java.awt.Color(255, 255, 255));
        GuiStrokeLineJoin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuiStrokeLineCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GuiStrokeLineJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(GuiStrokeLineCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GuiStrokeLineJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuiStrokeDashes, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuiStrokeDashes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.geotools.gui.swing.extended.JNumberPanel GuiStrokeAlpha;
    private org.geotools.gui.swing.style.sld.JColorPanel GuiStrokeColor;
    private org.geotools.gui.swing.style.sld.JDashPanel GuiStrokeDashes;
    private org.geotools.gui.swing.style.sld.JLinecapPanel GuiStrokeLineCap;
    private org.geotools.gui.swing.style.sld.JLinejoinPanel GuiStrokeLineJoin;
    private org.geotools.gui.swing.extended.JNumberPanel GuiStrokeWidth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_b_alpha;
    private javax.swing.JLabel lbl_b_color;
    private javax.swing.JLabel lbl_b_width;
    // End of variables declaration//GEN-END:variables
}