/* Generated By:JJTree: Do not edit this line. /home/gabriel/workspaces/svn/gt_trunk/gt/module/main/target/generated-src/main/java/org/geotools/filter/parser/ExpressionParserVisitor.java */

package org.geotools.filter.parser;

public interface ExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
