/*
 * JMap2DInfoBar.java
 *
 * Created on 5 octobre 2007, 11:49
 */
package org.geotools.gui.swing.map.map2d.control;

import javax.swing.JDialog;
import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.gui.swing.map.Map;
import org.geotools.gui.swing.map.map2d.JDefaultMap2D;
import org.geotools.gui.swing.map.map2d.Map2D;

/**
 * JMap2DInfoBar is a JPanel with a button to edit the GTRenderer and Rendering Strategy of the Map2D
 * @author johann Sorel
 */
public class JMap2DInfoBar extends javax.swing.JPanel {

    private Map2D map;

    /** 
     * Creates new form JMap2DInfoBar 
     */
    public JMap2DInfoBar() {
        initComponents();


    }

    /**
     * set the related Map2D
     * @param map : related Map2D
     */
    public void setMap(Map2D map) {

        if (map instanceof Map2D) {
            this.map = (Map2D) map;
            m_coord.setMap(map);
        }

        if (map instanceof JDefaultMap2D) {
            gui_config.setEnabled(true);
        } else {
            gui_config.setEnabled(false);
        }

    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gui_config = new javax.swing.JButton();
        m_coord = new org.geotools.gui.swing.map.map2d.control.JMap2DMouseCoordPanel();

        gui_config.setIcon(IconBundle.getResource().getIcon("16_map2d_optimize"));
        gui_config.setEnabled(false);
        gui_config.setMargin(new java.awt.Insets(2, 2, 2, 2));
        gui_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gui_configActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(gui_config, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(m_coord, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(gui_config, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
            .add(m_coord, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gui_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gui_configActionPerformed
        if (map != null && map instanceof JDefaultMap2D) {
            
            JMap2DConfigPanel opt = new JMap2DConfigPanel();
            opt.setMap((JDefaultMap2D)map);
                        
            JDialog dia = new JDialog();
            dia.setContentPane(opt);
            
            dia.pack();
            dia.setLocationRelativeTo(null);
            dia.setVisible(true);
            dia.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        }
        
        
}//GEN-LAST:event_gui_configActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton gui_config;
    private org.geotools.gui.swing.map.map2d.control.JMap2DMouseCoordPanel m_coord;
    // End of variables declaration//GEN-END:variables
}
