/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2006, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.map.map2d.event;

import java.util.EventObject;

import org.geotools.gui.swing.map.map2d.SelectableMap2D;
import org.geotools.gui.swing.map.map2d.SelectableMap2D.SELECTION_FILTER;
import org.geotools.gui.swing.map.map2d.handler.SelectionHandler;

import com.vividsolutions.jts.geom.Geometry;

/**
 * Selection Event generated by a SelectableMap2D
 * @author Johann Sorel
 */
public class Map2DSelectionEvent extends EventObject{

    private Geometry env = null;
    private SELECTION_FILTER filter = null;
    private SelectionHandler handler = null;
    
    
    /**
     * create a Map2DSelectionEvent
     * @param map : Map2D source componant
     * @param geo : JTS Geometry  of the selection or null
     * @param filter : SELECTION_FILTER
     * @param handler : SelectionHandler
     */
    public Map2DSelectionEvent(SelectableMap2D map, Geometry geo, SELECTION_FILTER filter, SelectionHandler handler){
        super(map);
        env = geo;
        this.filter = filter;
        this.handler = handler;
    }

    /**
     * Geometry corresponding to the selection zone.
     * Geometry is in the mapcontext CRS.
     * @return JTS Geometry, or null if no selection.
     */
    public Geometry getGeometry() {
        return env;
    }
    
    public SELECTION_FILTER getFilter() {
        return filter;
    }
    
    public SelectionHandler getHandler() {
        return handler;
    }
    
    
}
