/*
 *    GeoTools - OpenSource mapping toolkit
 *    http://geotools.org
 *    (C) 2002-2007, GeoTools Project Managment Committee (PMC)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotools.gui.swing.datachooser;

import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.swing.ImageIcon;
import javax.swing.event.EventListenerList;

import org.geotools.data.DataStore;
import org.geotools.data.DataStoreFinder;
import org.geotools.data.FeatureSource;
import org.geotools.data.postgis.PostgisDataStoreFactory;
import org.geotools.gui.swing.datachooser.model.DBModel;
import org.geotools.gui.swing.i18n.TextBundle;
import org.geotools.gui.swing.icon.IconBundle;
import org.geotools.gui.swing.misc.Render.RandomStyleFactory;
import org.geotools.map.DefaultMapLayer;
import org.geotools.map.MapLayer;
import org.geotools.styling.Style;

/**
 *
 * @author johann sorel
 */
public class JDatabaseDataPanel extends javax.swing.JPanel implements DataPanel {

    private DataStore store;
    private EventListenerList listeners = new EventListenerList();
    
    /** Creates new form DefaultShapeTypeChooser */
    public JDatabaseDataPanel() {
        initComponents();

        lbl_dbtype.setText(TextBundle.getResource().getString("dbtype"));
        lbl_host.setText(TextBundle.getResource().getString("host"));
        lbl_port.setText(TextBundle.getResource().getString("port"));
        lbl_schema.setText(TextBundle.getResource().getString("schema"));
        lbl_database.setText(TextBundle.getResource().getString("database"));
        lbl_user.setText(TextBundle.getResource().getString("user"));
        lbl_password.setText(TextBundle.getResource().getString("password"));
        but_refresh.setText(TextBundle.getResource().getString("refresh"));
        but_add.setText(TextBundle.getResource().getString("add"));

        tab_table.setTableHeader(null);
        tab_table.setModel(new DBModel(tab_table));
    }

    public Map getProperties() {
        Map config = new HashMap();
        config.put(PostgisDataStoreFactory.DBTYPE.key, jcb_dbtype.getSelectedItem());
        config.put(PostgisDataStoreFactory.HOST.key, txt_host.getText());
        config.put(PostgisDataStoreFactory.PORT.key, txt_port.getText());
        config.put(PostgisDataStoreFactory.SCHEMA.key,  txt_schema.getText());
        config.put(PostgisDataStoreFactory.DATABASE.key,  txt_database.getText());
        config.put(PostgisDataStoreFactory.USER.key,  txt_user.getText());
        config.put(PostgisDataStoreFactory.PASSWD.key,  String.valueOf(txt_password.getPassword()) );
        return config;
    }

    private void refreshTable(){
        
        if(store!= null){
            ((DBModel) tab_table.getModel()).clean();
            try {
                ((DBModel) tab_table.getModel()).add(store.getTypeNames());
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
        
    }
    
    private void fireEvent(MapLayer[] layers){
        for( DataListener lst : listeners.getListeners(DataListener.class)){
            lst.addLayers(layers);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_dbtype = new javax.swing.JLabel();
        txt_host = new javax.swing.JTextField();
        lbl_host = new javax.swing.JLabel();
        lbl_port = new javax.swing.JLabel();
        lbl_schema = new javax.swing.JLabel();
        lbl_database = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_port = new javax.swing.JTextField();
        txt_schema = new javax.swing.JTextField();
        txt_database = new javax.swing.JTextField();
        txt_user = new javax.swing.JTextField();
        but_refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_table = new org.jdesktop.swingx.JXTable();
        jcb_dbtype = new javax.swing.JComboBox();
        txt_password = new javax.swing.JPasswordField();
        but_add = new javax.swing.JButton();

        lbl_dbtype.setText("jLabel1");

        txt_host.setText("localhost");

        lbl_host.setText("jLabel2");

        lbl_port.setText("jLabel3");

        lbl_schema.setText("jLabel4");

        lbl_database.setText("jLabel5");

        lbl_user.setText("jLabel6");

        lbl_password.setText("jLabel7");

        txt_port.setText("5432");

        txt_schema.setText("default");

        but_refresh.setText("jButton1");
        but_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionRefresh(evt);
            }
        });

        tab_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tab_table);

        jcb_dbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "postgis" }));

        but_add.setText("jButton1");
        but_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAdd(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(but_refresh))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(lbl_dbtype)
                                .add(18, 18, 18)
                                .add(jcb_dbtype, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lbl_host)
                                .add(18, 18, 18)
                                .add(txt_host, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lbl_database)
                                .add(18, 18, 18)
                                .add(txt_database, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lbl_user)
                                .add(18, 18, 18)
                                .add(txt_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lbl_password)
                                .add(18, 18, 18)
                                .add(txt_password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lbl_port)
                                .add(18, 18, 18)
                                .add(txt_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(lbl_schema)
                                .add(18, 18, 18)
                                .add(txt_schema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, but_add)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jcb_dbtype, txt_database, txt_host, txt_password, txt_port, txt_schema, txt_user}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {lbl_database, lbl_dbtype, lbl_host, lbl_password, lbl_port, lbl_schema, lbl_user}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(but_add))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbl_dbtype)
                            .add(jcb_dbtype, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbl_host)
                            .add(txt_host, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbl_port)
                            .add(txt_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbl_schema)
                            .add(txt_schema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbl_database)
                            .add(txt_database, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbl_user)
                            .add(txt_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbl_password)
                            .add(txt_password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(but_refresh)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {jcb_dbtype, txt_database, txt_host, txt_password, txt_port, txt_schema, txt_user}, org.jdesktop.layout.GroupLayout.VERTICAL);

        layout.linkSize(new java.awt.Component[] {lbl_database, lbl_dbtype, lbl_host, lbl_password, lbl_port, lbl_schema, lbl_user}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void actionRefresh(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionRefresh
        
        try {
            store = DataStoreFinder.getDataStore(getProperties());
            refreshTable();
        } catch (IOException ex) {
            store = null;
            System.out.println(ex);
        }       
        
    }//GEN-LAST:event_actionRefresh

    private void actionAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAdd
       ArrayList<MapLayer> layers = new ArrayList<MapLayer>();
        
        if(store!=null){
            
            for(int i=0;i<tab_table.getSelectedRows().length; i++){
                try {
                    DBModel model = (DBModel) tab_table.getModel();
                    String name = (String) model.getValueAt( tab_table.getSelectedRows()[i],0);
                    FeatureSource fs = store.getFeatureSource(name);
                    Style style = RandomStyleFactory.createRandomVectorStyle(fs);
                    
                    MapLayer layer = new DefaultMapLayer(fs,style);
                    layer.setTitle( jcb_dbtype.getSelectedItem().toString() +"-"+ name);
                    layers.add(layer);
                } catch (IOException ex) {
                    System.out.println(ex);
                }                
            }
            
            if(layers.size()>0){
                MapLayer[] lys = new MapLayer[layers.size()];
                for(int i=0;i<layers.size();i++){
                    lys[i] =  layers.get(i);
                }
                fireEvent( lys );
            }
        }
    }//GEN-LAST:event_actionAdd

    public ImageIcon getIcon16() {
        return IconBundle.getResource().getIcon("16_database");
    }

    public ImageIcon getIcon48() {
        return IconBundle.getResource().getIcon("48_database");
    }

    public String getTitle() {
        return TextBundle.getResource().getString("database");
    }

    public Component getChooserComponent() {
        return this;
    }

    public void addListener(DataListener listener) {
        listeners.add(DataListener.class, listener);
    }

    public void removeListener(DataListener listener) {
        listeners.remove(DataListener.class, listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_add;
    private javax.swing.JButton but_refresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcb_dbtype;
    private javax.swing.JLabel lbl_database;
    private javax.swing.JLabel lbl_dbtype;
    private javax.swing.JLabel lbl_host;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_port;
    private javax.swing.JLabel lbl_schema;
    private javax.swing.JLabel lbl_user;
    private org.jdesktop.swingx.JXTable tab_table;
    private javax.swing.JTextField txt_database;
    private javax.swing.JTextField txt_host;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_schema;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}