/*
 * JDataChooser.java
 *
 * Created on 24 octobre 2007, 19:10
 */
package org.geotools.gui.swing.datachooser;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JTabbedPane;
import org.geotools.gui.swing.datachooser.model.DataModel;
import org.geotools.map.MapLayer;

/**
 *
 * @author johann sorel
 */
public class JDataChooser extends javax.swing.JDialog implements DataListener {

    public static enum ACTION{
        APPROVE,
        CANCEL,
        CLOSE
    };
    
    private ACTION exitmode = ACTION.CLOSE;
    private ArrayList<DataPanel> types = new ArrayList<DataPanel>();
    private ButtonGroup group;
    private JTabbedPane tabbedpane = new JTabbedPane();

    /** Creates new form JDataChooser */
    public JDataChooser(java.awt.Frame parent,List<DataPanel> type) {
        super(parent,true);
        initComponents();

        pan_source.setLayout(new GridLayout(1, 1));
        tabbedpane = new JTabbedPane();

        tab_data.setModel(new DataModel(tab_data));
        tab_data.setTableHeader(null);
        
        setDataTypeChooser(type);

    }

    public void setDataTypeChooser(List<DataPanel> type) {

        for (DataPanel pan : types) {
            pan.removeListener(this);
        }

        types.clear();
        types.addAll(type);


        if (types.size() == 1) {
            setPanel(types.get(0));
        } else if (types.size() > 1) {
            panel.removeAll();
            panel.setLayout(new GridLayout(1, 1));
            tabbedpane.removeAll();
            panel.add(tabbedpane);
            for (DataPanel pan : types) {
                pan.addListener(this);
                tabbedpane.addTab(pan.getTitle(), pan.getIcon16(), pan.getChooserComponent());
            }
            panel.revalidate();
            panel.repaint();
        }

    }

    private void removeselected() {
        ((DataModel) tab_data.getModel()).removeSelected();
    }

    private void setPanel(DataPanel comp) {
        if (pan_source != null) {
            txt_title.setTitle(comp.getTitle());
            pan_source.removeAll();
            pan_source.add(comp.getChooserComponent());
            pan_source.revalidate();
            pan_source.repaint();
        }
    }

    public List<MapLayer> getLayers() {
        return ((DataModel) tab_data.getModel()).getLayers();
    }

    public void addLayers(MapLayer[] layers) {
        ((DataModel) tab_data.getModel()).addLayer(layers);
    }

    public ACTION showDialog() {
        exitmode = ACTION.CLOSE;
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        return exitmode;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        but_remove = new javax.swing.JButton();
        but_valider = new javax.swing.JButton();
        but_fermer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_data = new org.jdesktop.swingx.JXTable();
        txt_datas = new org.jdesktop.swingx.JXTitledSeparator();
        panel = new javax.swing.JPanel();
        txt_title = new org.jdesktop.swingx.JXTitledSeparator();
        pan_source = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/geotools/gui/swing/datachooser/Bundle"); // NOI18N
        setTitle(bundle.getString("add_data_dialog")); // NOI18N

        but_remove.setText(bundle.getString("remove")); // NOI18N
        but_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_removeactionRemove(evt);
            }
        });

        but_valider.setText(bundle.getString("apply")); // NOI18N
        but_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_valideractionAjouter(evt);
            }
        });

        but_fermer.setText(bundle.getString("cancel")); // NOI18N
        but_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_fermeractionFermer(evt);
            }
        });

        jScrollPane1.setBorder(null);

        tab_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab_data);

        txt_datas.setTitle(bundle.getString("layers")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(but_remove)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                .add(but_valider)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(but_fermer))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_datas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(txt_datas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(but_fermer)
                    .add(but_valider)
                    .add(but_remove))
                .addContainerGap())
        );

        txt_title.setTitle("");

        org.jdesktop.layout.GroupLayout pan_sourceLayout = new org.jdesktop.layout.GroupLayout(pan_source);
        pan_source.setLayout(pan_sourceLayout);
        pan_sourceLayout.setHorizontalGroup(
            pan_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 396, Short.MAX_VALUE)
        );
        pan_sourceLayout.setVerticalGroup(
            pan_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 315, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout panelLayout = new org.jdesktop.layout.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(txt_title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
            .add(pan_source, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(txt_title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pan_source, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void but_removeactionRemove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_removeactionRemove
        removeselected();
    }//GEN-LAST:event_but_removeactionRemove

    private void but_valideractionAjouter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_valideractionAjouter
        exitmode = ACTION.APPROVE;
        dispose();
}//GEN-LAST:event_but_valideractionAjouter

    private void but_fermeractionFermer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_fermeractionFermer
        exitmode = ACTION.CANCEL;
        dispose();
    }//GEN-LAST:event_but_fermeractionFermer
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_fermer;
    private javax.swing.JButton but_remove;
    private javax.swing.JButton but_valider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pan_source;
    private javax.swing.JPanel panel;
    private org.jdesktop.swingx.JXTable tab_data;
    private org.jdesktop.swingx.JXTitledSeparator txt_datas;
    private org.jdesktop.swingx.JXTitledSeparator txt_title;
    // End of variables declaration//GEN-END:variables
}
